### ISSUE TITLE
EU GDPR consent 

### ISSUE THREAD

**Issue by attilaoroszdev** [Squatnet/AdmobAndShare#1]
Just a suggestion:

Google will start enforcing GDPR consent in the EU/EEA soon (tomorrow, in fact). It might be worth updating the AdMob parts with those bits.

I just cobbled together a plugin that can be used to parse consent statuses, amd check for issues. It can be used with Shin-Nil's stuff, or any other working AdMob plugin:

https://github.com/attilaoroszdev/godoteuconsentparserplugin

**Comment by Squatnet** [comment]
Please dont use the Github issues to spam dead projects about your project.
It wont get people to use it.
It'll just piss them off.
Thanks
